apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-sample-ntte
  namespace: cnpg-system
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3
  minSyncReplicas: 1
  maxSyncReplicas: 1
  postgresql:
    parameters:
      archive_mode: "on"
      archive_timeout: 5min
      tcp_keepalives_idle: '600'
      tcp_keepalives_interval: '60'
      tcp_keepalives_count: '6'

  storage:
    storageClass: lvms-vg1
    size: 2Gi

  walStorage:
    storageClass: lvms-vg1
    size: 2Gi

  backup:
    barmanObjectStore:
      data:
        immediateCheckpoint: true
      destinationPath: 's3://cohesity-test/'
      endpointCA:
        key: ca.crt
        name: my-ca-secret-test
      endpointURL: 'https://backup-sv.cohesity.com:3000'
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: cohesity-creds
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: cohesity-creds
    retentionPolicy: 1d
    target: prefer-standby

  monitoring:
    enablePodMonitor: true
