apiVersion: v1
kind: ConfigMap
metadata:
  name: example-monitoring
  namespace: <namespace>
  labels:
    cnpg.io/reload: ""
data:
  custom-queries: |
    pg_replication:
      query: "SELECT CASE WHEN NOT pg_is_in_recovery()
              THEN 0
              ELSE GREATEST (0,
                EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp())))
              END AS lag,
              pg_is_in_recovery() AS in_recovery,
              EXISTS (TABLE pg_stat_wal_receiver) AS is_wal_receiver_up,
              (SELECT count(*) FROM pg_stat_replication) AS streaming_replicas"
      metrics:
        - lag:
            usage: "GAUGE"
            description: "Replication lag behind primary in seconds"
        - in_recovery:
            usage: "GAUGE"
            description: "Whether the instance is in recovery"
        - is_wal_receiver_up:
            usage: "GAUGE"
            description: "Whether the instance wal_receiver is up"
        - streaming_replicas:
            usage: "GAUGE"
            description: "Number of streaming replicas connected to the instance"

    some_query:
      query: |
        SELECT
         current_database() as datname,
         count(*) as rows
        FROM some_table
      metrics:
        - datname:
            usage: "LABEL"
            description: "Name of current database"
        - rows:
            usage: "GAUGE"
            description: "number of rows"
      target_databases:
        - postgres

    custom_aaa:
      query: "SELECT count(*) AS active_conn FROM pg_stat_activity WHERE state = 'active';"
      metrics:
        - active_conn:
            usage: "GAUGE"
            description: "Number of active connections"
